services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    env_file: .env
    networks:
      - inception-network
    volumes:
      - mariadb_data:/var/lib/mysql
    pull_policy: never
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 15s
      timeout: 5s
      retries: 5

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    env_file: .env
    networks:
      - inception-network
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
      - redis
    pull_policy: never
    restart: unless-stopped

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - inception-network
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
      - static-website
      - adminer
    pull_policy: never
    restart: unless-stopped

  #bonus

  redis:
    build:
      context: ./bonus/redis
      dockerfile: Dockerfile
    container_name: redis
    env_file: .env
    networks:
      - inception-network
    pull_policy: never
    restart: unless-stopped

  static-website:
    build:
      context: ./bonus/static-website
      dockerfile: Dockerfile
    container_name: static-website
    networks:
      - inception-network
    volumes:
      - wordpress_data:/var/www/html
    pull_policy: never
    restart: on-failure:2

  adminer:
    build:
      context: ./bonus/adminer
      dockerfile: Dockerfile
    container_name: adminer
    networks:
      - inception-network
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    restart: unless-stopped

  ftp-server:
    container_name: ftp-server
    build:
      context: ./bonus/ftp
      dockerfile: Dockerfile
    init: true
    env_file:
      - .env
    networks:
      - inception-network
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "21-21:21-21"
      - "20000-20100:20000-20100"
    pull_policy: never
    restart: unless-stopped


  # ftp:
  #   build:
  #     context: ./bonus/ftp
  #     dockerfile: Dockerfile
  #     args:
  #       FTP_USER: ${FTP_USER}        # Build arg olarak FTP_USER ekledik
  #       FTP_PASSWORD: ${FTP_PASSWORD} # Build arg olarak FTP_PASSWORD ekledik
  #   container_name: ftp
  #   env_file: .env
  #   networks:
  #     - inception-network
  #   volumes:
  #     - wordpress_data:/home/${FTP_USER} # Volume'u dinamik hale getirdik
  #   ports:
  #     - "21:21"
  #     - "21000-21010:21000-21010"
  #   depends_on:
  #     - wordpress
  #   pull_policy: never
  #   restart: unless-stopped


networks:
  inception-network:
    driver: bridge
  
volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/wordpress_data
      o: bind
  
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/mariadb_data
      o: bind

  static_data:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/static_data
      o: bind
