services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    env_file: .env
    networks:
      - inception-network
    volumes:
      - mariadb_data:/var/lib/mysql
    pull_policy: never
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 15s
      timeout: 5s
      retries: 5

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    env_file: .env
    networks:
      - inception-network
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
      - redis
    pull_policy: never
    restart: unless-stopped

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - inception-network
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
      - static-website
      - adminer
    pull_policy: never
    restart: unless-stopped

  #bonus

  redis:
    build:
      context: ./bonus/redis
      dockerfile: Dockerfile
    container_name: redis
    env_file: .env
    networks:
      - inception-network
    pull_policy: never
    restart: unless-stopped

  static-website:
    build:
      context: ./bonus/static-website
      dockerfile: Dockerfile
    container_name: static-website
    networks:
      - inception-network
    volumes:
      - wordpress_data:/var/www/html
    pull_policy: never
    restart: on-failure:2

  adminer:
    build:
      context: ./bonus/adminer
      dockerfile: Dockerfile
    container_name: adminer
    networks:
      - inception-network
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    restart: unless-stopped

  # ftp:
  #   container_name: ftp
  #   build:
  #     context: ./bonus/ftp
  #     dockerfile: Dockerfile
  #   env_file:
  #     - .env
  #   networks:
  #     - inception-network
  #   volumes:
  #     - wordpress_data:/var/www/html
  #   ports:
  #     - "21-21:21-21"
  #     - "20000-20100:20000-20100"
  #   pull_policy: never
  #   restart: unless-stopped

  prometheus:
    build:
      context: ./bonus/prometheus
      dockerfile: Dockerfile
    container_name: prometheus
    networks:
      - inception-network
    volumes:
      - prometheus_data:/tmp/prometheus
    pull_policy: never
    restart: unless-stopped

  node-exporter:
    build:
      context: ./bonus/node-exporter
      dockerfile: Dockerfile
    container_name: node-exporter
    networks:
      - inception-network
    # Host metriklerini doğru şekilde okuyabilmek için /proc ve /sys gibi 
    # mountlar ekleyebilirsiniz (örnek aşağıda):
    # volumes:
    #   - /proc:/host/proc:ro
    #   - /sys:/host/sys:ro
    # command:
    #   - '--path.procfs=/host/proc'
    #   - '--path.sysfs=/host/sys'
    pull_policy: never
    restart: unless-stopped

  grafana:
    build:
      context: ./bonus/grafana
      dockerfile: Dockerfile
    container_name: grafana
    networks:
      - inception-network
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    restart: unless-stopped
    env_file: .env
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      # - GF_SERVER_DOMAIN=grafana.tkaragoz.42.fr
      # - GF_SERVER_ROOT_URL=https://grafana.tkaragoz.42.fr/
      # # Self-signed sertifika vs. varsa:
      # - GF_SECURITY_ALLOW_EMBEDDING=true
      # - GF_SECURITY_COOKIE_SAMESITE=none
      # - GF_SERVER_SERVE_FROM_SUB_PATH=true
    pull_policy: never


networks:
  inception-network:
    driver: bridge
  
volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/wordpress_data
      o: bind
  
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/mariadb_data
      o: bind

  static_data:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/static_data
      o: bind

  prometheus_data:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/prometheus_data
      o: bind

  grafana_data:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/grafana_data
      o: bind
