# General Settings
listen=YES
listen_port=21

# User Settings
anonymous_enable=YES
local_enable=YES
write_enable=YES
local_umask=022


# Passive Mode Settings
pasv_enable=YES
pasv_min_port=20000
pasv_max_port=20100
pasv_address=ftp.tkaragoz.42.fr

# User List Settings
userlist_enable=YES
userlist_file=/etc/vsftpd.userlist
userlist_deny=NO

# Root Directory Settings
local_root=/var/www/html

# Secure Chroot Directory
chroot_local_user=YES
allow_writeable_chroot=YES
secure_chroot_dir=/var/run/vsftpd/empty

# FTP Banner
ftpd_banner=Welcome to FTP Server: ftp.tkaragoz.42.fr!

