# Genel Ayarlar
listen=YES
listen_port=21
listen_address=0.0.0.0
seccomp_sandbox=NO

# Kullanıcı Ayarları
anonymous_enable=YES
local_enable=YES
write_enable=YES
local_umask=022
dirmessage_enable=YES
use_localtime=YES
xferlog_enable=YES
connect_from_port_20=YES
pam_service_name=vsftpd

# SSL Ayarları (Geçici olarak devre dışı bırakıldı)
ssl_enable=NO
allow_anon_ssl=NO
force_local_data_ssl=NO
force_local_logins_ssl=NO
ssl_tlsv1=YES
ssl_sslv2=NO
ssl_sslv3=NO

# Pasif Mod Ayarları
pasv_enable=YES
pasv_min_port=20000
pasv_max_port=20100
pasv_address=ftp.tkaragoz.42.fr  # Sunucunuzun gerçek dış IP adresini buraya ekleyin

# Kullanıcı Listesi Ayarları
userlist_enable=YES
userlist_file=/etc/vsftpd.userlist
userlist_deny=NO

# Root Dizini Ayarları
user_sub_token=$USER
local_root=/var/www/html

# Güvenli Chroot Dizini
chroot_local_user=YES
allow_writeable_chroot=YES
secure_chroot_dir=/var/run/vsftpd/empty

# Banner Mesajı
ftpd_banner=Welcome to Inception FTP server!
